version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    volumes:
      - ./db:/db
      - ./db/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./scripts:/scripts
    ports:
        - "5432:5432"
  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
        - postgres
    environment:
        - LOAD_EX=n
        - EXECUTOR=Local
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=airflow
    logging:
        options:
            max-size: 10m
            max-file: "3"
    volumes:
        - ./etl:/usr/local/airflow/dags
        - ./sql:/usr/local/airflow/dags/sql
        - ./data:/data
    ports:
        - "8080:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3