#!/bin/sh

until PGPASSWORD=postgres psql --host postgres --username postgres -c '\l' > /dev/null; do
  echo "Postgres is unavailable - sleeping"
  sleep 1
done
echo "Connected Postgres - running"

apt-get update

PGPASSWORD=postgres psql --host postgres --username postgres -f ./db/initial.sql


export PYTHONUNBUFFERED=0